server:
  port: 9010
  forward-headers-strategy: framework

spring:
  application:
    name: walkdog-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/database_name}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 900000
      connection-timeout: 10000
      validation-timeout: 5000
      keepalive-time: 300000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

walkdog:
  oauth:
    jwk-set-uri: ${JWT_SET_URL:http://localhost:9011/auth/.well-known/jwks.json}
    token-uri: ${TOKEN_URL:http://localhost:9011/oauth2/token}

logging:
  level:
    jdbc:
      audit: OFF
      resultset: OFF
      sqlonly: OFF
      sqltiming: INFO
      connection: OFF
      resultsettable: OFF
